### ISSUE TITLE
Feature: add proftpd::ftpasswd::user defined type

### ISSUE THREAD

**Issue by cedef** [fraenki/puppet-proftpd#18]
I would like to add a `proftpd::ftpasswd::user` defined type in order to declare virtual users as simple variables like:

```yaml
proftpd::virtual_users
    foo:
      password: $1$nVw4HoT7$VhFX6HFiz4VzbYnWUFrNP.
      uid: 33
      gid: 33
      homedir: /home/foo
      shell: /bin/false
```

Implementation would be trivial and using a concat::fragment targeting `$proftpd::params::ftpasswd_file`.

Would you accept a patch for such feature ?
